name: Balls

on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies (generates package-lock.json)
      run: npm install

    - name: Build project
      run: npm run build

    - name: Format code
      run: npm run format

    - name: Upload generated package-lock.json
      uses: actions/upload-artifact@v4
      with:
        name: package-lock-generated
        path: package-lock.json

    - name: Upload dist folder
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: dist/
